#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/java_blog_spring?characterEncoding=utf8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  file:
#    name: spring-blog.log
#  level:
#    # 生产环境可以关闭MyBatis SQL日志
#    com.bit.blog: DEBUG
#    org.springframework.web.servlet.resource: WARN
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_blog_spring?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: spring-blog.log